#!/usr/bin/env bash
#Usage: ./1-world_wide_web <domain> <subdomain>
#Display Information about subdomains

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
  subdomains=("www" "lb-01" "web-01" "web-02")
else
  subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
  record_type=$(dig +short "$sub.$domain" | awk '{print $4}')
  destination=$(dig +short "$sub.$domain" | awk '{print $5}')
  echo "The subdomain $sub is a $record_type record and points to $destination"
done
