#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#    Enables management via the init script.
#    Distributes requests using a round-robin algorithm.

apt update -y
apt upgrade -y
apt install haproxy -y
echo -e "\nfrontend web_frontend\n\tbind *:80\n\tdefault_backend web_backend" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend web_backend\n\tbalance roundrobin\n\tserver web-01 100.25.142.179:80 check\n\tserver web-02 54.197.124.78:80 check" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy restart
