#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#    Enables management via the init script.
#    Distributes requests using a round-robin algorithm.

apt update -y
apt upgrade -y
apt install haproxy -y
echo -e "\nfrontend web_frontend\n\tbind *:80\n\tdefault_backend web_backend" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend web_backend\n\tbalance roundrobin\n\tserver web-01 18.215.160.88:80 check\n\tserver web-02 34.224.2.183:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
