#!/usr/bin/env bash
#Do the require task

terminator() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && terminator' SIGTERM
trap 'terminator' SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
