#!/usr/bin/env bash
#manage the file manage_my_process

case "$1" in
	start)
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		kill "$(pgrep -f /manage_my_process)"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		kill "$(pgrep -f /manage_my_process)"
		rm /var/run/my_process.pid
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		;;
esac
