#!/usr/bin/env bash
#manage the file manage_my_process

case "$1" in
	start)
		./manage_my_process &
		echo $! > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		pkill -F /var/run/my_process.pid
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
